// ESPN Official Soccer Club Logos Helper & Mapping (Verified Live CDN URLs)

export const DEFAULT_TEAM_LOGO = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 48 48' fill='none'><circle cx='24' cy='24' r='22' fill='%23facc15' stroke='%23ca8a04' stroke-width='2.5'/><circle cx='24' cy='24' r='16' fill='%230f172a'/><polygon points='24,12 33,18 29.5,29 18.5,29 15,18' fill='%23ffffff'/><circle cx='24' cy='24' r='21' stroke='%23000000' stroke-width='1.5' stroke-opacity='0.2'/></svg>";

export const ESPN_TEAM_LOGOS: Record<string, string> = {
  "83": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
  "85": "https://a.espncdn.com/i/teamlogos/soccer/500/85.png",
  "86": "https://a.espncdn.com/i/teamlogos/soccer/500/86.png",
  "87": "https://a.espncdn.com/i/teamlogos/soccer/500/87.png",
  "88": "https://a.espncdn.com/i/teamlogos/soccer/500/88.png",
  "89": "https://a.espncdn.com/i/teamlogos/soccer/500/89.png",
  "90": "https://a.espncdn.com/i/teamlogos/soccer/500/90.png",
  "93": "https://a.espncdn.com/i/teamlogos/soccer/500/93.png",
  "94": "https://a.espncdn.com/i/teamlogos/soccer/500/94.png",
  "96": "https://a.espncdn.com/i/teamlogos/soccer/500/96.png",
  "97": "https://a.espncdn.com/i/teamlogos/soccer/500/97.png",
  "99": "https://a.espncdn.com/i/teamlogos/soccer/500/99.png",
  "101": "https://a.espncdn.com/i/teamlogos/soccer/500/101.png",
  "102": "https://a.espncdn.com/i/teamlogos/soccer/500/102.png",
  "103": "https://a.espncdn.com/i/teamlogos/soccer/500/103.png",
  "104": "https://a.espncdn.com/i/teamlogos/soccer/500/104.png",
  "105": "https://a.espncdn.com/i/teamlogos/soccer/500/105.png",
  "107": "https://a.espncdn.com/i/teamlogos/soccer/500/107.png",
  "109": "https://a.espncdn.com/i/teamlogos/soccer/500/109.png",
  "110": "https://a.espncdn.com/i/teamlogos/soccer/500/110.png",
  "111": "https://a.espncdn.com/i/teamlogos/soccer/500/111.png",
  "112": "https://a.espncdn.com/i/teamlogos/soccer/500/112.png",
  "113": "https://a.espncdn.com/i/teamlogos/soccer/500/113.png",
  "114": "https://a.espncdn.com/i/teamlogos/soccer/500/114.png",
  "115": "https://a.espncdn.com/i/teamlogos/soccer/500/115.png",
  "118": "https://a.espncdn.com/i/teamlogos/soccer/500/118.png",
  "122": "https://a.espncdn.com/i/teamlogos/soccer/500/122.png",
  "124": "https://a.espncdn.com/i/teamlogos/soccer/500/124.png",
  "125": "https://a.espncdn.com/i/teamlogos/soccer/500/125.png",
  "126": "https://a.espncdn.com/i/teamlogos/soccer/500/126.png",
  "127": "https://a.espncdn.com/i/teamlogos/soccer/500/127.png",
  "131": "https://a.espncdn.com/i/teamlogos/soccer/500/131.png",
  "132": "https://a.espncdn.com/i/teamlogos/soccer/500/132.png",
  "133": "https://a.espncdn.com/i/teamlogos/soccer/500/133.png",
  "134": "https://a.espncdn.com/i/teamlogos/soccer/500/134.png",
  "137": "https://a.espncdn.com/i/teamlogos/soccer/500/137.png",
  "142": "https://a.espncdn.com/i/teamlogos/soccer/500/142.png",
  "148": "https://a.espncdn.com/i/teamlogos/soccer/500/148.png",
  "160": "https://a.espncdn.com/i/teamlogos/soccer/500/160.png",
  "166": "https://a.espncdn.com/i/teamlogos/soccer/500/166.png",
  "167": "https://a.espncdn.com/i/teamlogos/soccer/500/167.png",
  "169": "https://a.espncdn.com/i/teamlogos/soccer/500/169.png",
  "170": "https://a.espncdn.com/i/teamlogos/soccer/500/170.png",
  "172": "https://a.espncdn.com/i/teamlogos/soccer/500/172.png",
  "174": "https://a.espncdn.com/i/teamlogos/soccer/500/174.png",
  "175": "https://a.espncdn.com/i/teamlogos/soccer/500/175.png",
  "176": "https://a.espncdn.com/i/teamlogos/soccer/500/176.png",
  "179": "https://a.espncdn.com/i/teamlogos/soccer/500/179.png",
  "180": "https://a.espncdn.com/i/teamlogos/soccer/500/180.png",
  "239": "https://a.espncdn.com/i/teamlogos/soccer/500/239.png",
  "243": "https://a.espncdn.com/i/teamlogos/soccer/500/243.png",
  "244": "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
  "268": "https://a.espncdn.com/i/teamlogos/soccer/500/268.png",
  "273": "https://a.espncdn.com/i/teamlogos/soccer/500/273.png",
  "306": "https://a.espncdn.com/i/teamlogos/soccer/500/306.png",
  "331": "https://a.espncdn.com/i/teamlogos/soccer/500/331.png",
  "337": "https://a.espncdn.com/i/teamlogos/soccer/500/337.png",
  "349": "https://a.espncdn.com/i/teamlogos/soccer/500/349.png",
  "357": "https://a.espncdn.com/i/teamlogos/soccer/500/357.png",
  "359": "https://a.espncdn.com/i/teamlogos/soccer/500/359.png",
  "360": "https://a.espncdn.com/i/teamlogos/soccer/500/360.png",
  "361": "https://a.espncdn.com/i/teamlogos/soccer/500/361.png",
  "362": "https://a.espncdn.com/i/teamlogos/soccer/500/362.png",
  "363": "https://a.espncdn.com/i/teamlogos/soccer/500/363.png",
  "364": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
  "366": "https://a.espncdn.com/i/teamlogos/soccer/500/366.png",
  "367": "https://a.espncdn.com/i/teamlogos/soccer/500/367.png",
  "368": "https://a.espncdn.com/i/teamlogos/soccer/500/368.png",
  "370": "https://a.espncdn.com/i/teamlogos/soccer/500/370.png",
  "373": "https://a.espncdn.com/i/teamlogos/soccer/500/373.png",
  "382": "https://a.espncdn.com/i/teamlogos/soccer/500/382.png",
  "384": "https://a.espncdn.com/i/teamlogos/soccer/500/384.png",
  "388": "https://a.espncdn.com/i/teamlogos/soccer/500/388.png",
  "393": "https://a.espncdn.com/i/teamlogos/soccer/500/393.png",
  "432": "https://a.espncdn.com/i/teamlogos/soccer/500/432.png",
  "436": "https://a.espncdn.com/i/teamlogos/soccer/500/436.png",
  "437": "https://a.espncdn.com/i/teamlogos/soccer/500/437.png",
  "493": "https://a.espncdn.com/i/teamlogos/soccer/500/493.png",
  "494": "https://a.espncdn.com/i/teamlogos/soccer/500/494.png",
  "510": "https://a.espncdn.com/i/teamlogos/soccer/500/510.png",
  "521": "https://a.espncdn.com/i/teamlogos/soccer/500/521.png",
  "570": "https://a.espncdn.com/i/teamlogos/soccer/500/570.png",
  "598": "https://a.espncdn.com/i/teamlogos/soccer/500/598.png",
  "887": "https://a.espncdn.com/i/teamlogos/soccer/500/887.png",
  "1068": "https://a.espncdn.com/i/teamlogos/soccer/500/1068.png",
  "1538": "https://a.espncdn.com/i/teamlogos/soccer/500/1538.png",
  "2250": "https://a.espncdn.com/i/teamlogos/soccer/500/2250.png",
  "2502": "https://a.espncdn.com/i/teamlogos/soccer/500/2502.png",
  "2572": "https://a.espncdn.com/i/teamlogos/soccer/500/2572.png",
  "2697": "https://a.espncdn.com/i/teamlogos/soccer/500/2697.png",
  "2922": "https://a.espncdn.com/i/teamlogos/soccer/500/2922.png",
  "2925": "https://a.espncdn.com/i/teamlogos/soccer/500/2925.png",
  "2950": "https://a.espncdn.com/i/teamlogos/soccer/500/2950.png",
  "2980": "https://a.espncdn.com/i/teamlogos/soccer/500/2980.png",
  "3236": "https://a.espncdn.com/i/teamlogos/soccer/500/3236.png",
  "3263": "https://a.espncdn.com/i/teamlogos/soccer/500/3263.png",
  "3307": "https://a.espncdn.com/i/teamlogos/soccer/500/3307.png",
  "3751": "https://a.espncdn.com/i/teamlogos/soccer/500/3751.png",
  "3841": "https://a.espncdn.com/i/teamlogos/soccer/500/3841.png",
  "3997": "https://a.espncdn.com/i/teamlogos/soccer/500/3997.png",
  "4007": "https://a.espncdn.com/i/teamlogos/soccer/500/4007.png",
  "4057": "https://a.espncdn.com/i/teamlogos/soccer/500/4057.png",
  "4411": "https://a.espncdn.com/i/teamlogos/soccer/500/4411.png",
  "6851": "https://a.espncdn.com/i/teamlogos/soccer/500/6851.png",
  "6997": "https://a.espncdn.com/i/teamlogos/soccer/500/6997.png",
  "7868": "https://a.espncdn.com/i/teamlogos/soccer/500/7868.png",
  "7911": "https://a.espncdn.com/i/teamlogos/soccer/500/7911.png",
  "10388": "https://a.espncdn.com/i/teamlogos/soccer/500/10388.png",
  "11420": "https://a.espncdn.com/i/teamlogos/soccer/500/11420.png",
  "17530": "https://a.espncdn.com/i/teamlogos/soccer/500/17530.png",
  "21922": "https://a.espncdn.com/i/teamlogos/soccer/500/21922.png",
  "afc bournemouth": "https://a.espncdn.com/i/teamlogos/soccer/500/349.png",
  "bournemouth": "https://a.espncdn.com/i/teamlogos/soccer/500/349.png",
  "bou": "https://a.espncdn.com/i/teamlogos/soccer/500/349.png",
  "arsenal": "https://a.espncdn.com/i/teamlogos/soccer/500/359.png",
  "ars": "https://a.espncdn.com/i/teamlogos/soccer/500/359.png",
  "aston villa": "https://a.espncdn.com/i/teamlogos/soccer/500/362.png",
  "avl": "https://a.espncdn.com/i/teamlogos/soccer/500/362.png",
  "brentford": "https://a.espncdn.com/i/teamlogos/soccer/500/337.png",
  "bre": "https://a.espncdn.com/i/teamlogos/soccer/500/6997.png",
  "brighton & hove albion": "https://a.espncdn.com/i/teamlogos/soccer/500/331.png",
  "brighton": "https://a.espncdn.com/i/teamlogos/soccer/500/331.png",
  "bha": "https://a.espncdn.com/i/teamlogos/soccer/500/331.png",
  "chelsea": "https://a.espncdn.com/i/teamlogos/soccer/500/363.png",
  "che": "https://a.espncdn.com/i/teamlogos/soccer/500/363.png",
  "coventry city": "https://a.espncdn.com/i/teamlogos/soccer/500/388.png",
  "coventry": "https://a.espncdn.com/i/teamlogos/soccer/500/388.png",
  "cov": "https://a.espncdn.com/i/teamlogos/soccer/500/388.png",
  "crystal palace": "https://a.espncdn.com/i/teamlogos/soccer/500/384.png",
  "c palace": "https://a.espncdn.com/i/teamlogos/soccer/500/384.png",
  "cry": "https://a.espncdn.com/i/teamlogos/soccer/500/384.png",
  "everton": "https://a.espncdn.com/i/teamlogos/soccer/500/368.png",
  "eve": "https://a.espncdn.com/i/teamlogos/soccer/500/368.png",
  "fulham": "https://a.espncdn.com/i/teamlogos/soccer/500/370.png",
  "ful": "https://a.espncdn.com/i/teamlogos/soccer/500/370.png",
  "hull city": "https://a.espncdn.com/i/teamlogos/soccer/500/306.png",
  "hull": "https://a.espncdn.com/i/teamlogos/soccer/500/306.png",
  "hul": "https://a.espncdn.com/i/teamlogos/soccer/500/306.png",
  "ipswich town": "https://a.espncdn.com/i/teamlogos/soccer/500/373.png",
  "ipswich": "https://a.espncdn.com/i/teamlogos/soccer/500/373.png",
  "ips": "https://a.espncdn.com/i/teamlogos/soccer/500/373.png",
  "leeds united": "https://a.espncdn.com/i/teamlogos/soccer/500/357.png",
  "leeds": "https://a.espncdn.com/i/teamlogos/soccer/500/357.png",
  "lee": "https://a.espncdn.com/i/teamlogos/soccer/500/357.png",
  "liverpool": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
  "liv": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
  "manchester city": "https://a.espncdn.com/i/teamlogos/soccer/500/382.png",
  "man city": "https://a.espncdn.com/i/teamlogos/soccer/500/382.png",
  "mnc": "https://a.espncdn.com/i/teamlogos/soccer/500/382.png",
  "manchester united": "https://a.espncdn.com/i/teamlogos/soccer/500/360.png",
  "man united": "https://a.espncdn.com/i/teamlogos/soccer/500/360.png",
  "man": "https://a.espncdn.com/i/teamlogos/soccer/500/360.png",
  "newcastle united": "https://a.espncdn.com/i/teamlogos/soccer/500/361.png",
  "newcastle": "https://a.espncdn.com/i/teamlogos/soccer/500/361.png",
  "new": "https://a.espncdn.com/i/teamlogos/soccer/500/361.png",
  "nottingham forest": "https://a.espncdn.com/i/teamlogos/soccer/500/393.png",
  "nottm forest": "https://a.espncdn.com/i/teamlogos/soccer/500/393.png",
  "nfo": "https://a.espncdn.com/i/teamlogos/soccer/500/393.png",
  "sunderland": "https://a.espncdn.com/i/teamlogos/soccer/500/366.png",
  "sun": "https://a.espncdn.com/i/teamlogos/soccer/500/366.png",
  "tottenham hotspur": "https://a.espncdn.com/i/teamlogos/soccer/500/367.png",
  "spurs": "https://a.espncdn.com/i/teamlogos/soccer/500/367.png",
  "tot": "https://a.espncdn.com/i/teamlogos/soccer/500/367.png",
  "alavés": "https://a.espncdn.com/i/teamlogos/soccer/500/96.png",
  "ala": "https://a.espncdn.com/i/teamlogos/soccer/500/96.png",
  "athletic club": "https://a.espncdn.com/i/teamlogos/soccer/500/93.png",
  "athletic": "https://a.espncdn.com/i/teamlogos/soccer/500/93.png",
  "ath": "https://a.espncdn.com/i/teamlogos/soccer/500/93.png",
  "atlético madrid": "https://a.espncdn.com/i/teamlogos/soccer/500/1068.png",
  "atlético": "https://a.espncdn.com/i/teamlogos/soccer/500/1068.png",
  "atm": "https://a.espncdn.com/i/teamlogos/soccer/500/1068.png",
  "barcelona": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
  "bar": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
  "celta vigo": "https://a.espncdn.com/i/teamlogos/soccer/500/85.png",
  "cel": "https://a.espncdn.com/i/teamlogos/soccer/500/85.png",
  "deportivo": "https://a.espncdn.com/i/teamlogos/soccer/500/90.png",
  "dep": "https://a.espncdn.com/i/teamlogos/soccer/500/90.png",
  "elche": "https://a.espncdn.com/i/teamlogos/soccer/500/3751.png",
  "elc": "https://a.espncdn.com/i/teamlogos/soccer/500/3751.png",
  "espanyol": "https://a.espncdn.com/i/teamlogos/soccer/500/88.png",
  "esp": "https://a.espncdn.com/i/teamlogos/soccer/500/88.png",
  "getafe": "https://a.espncdn.com/i/teamlogos/soccer/500/2922.png",
  "get": "https://a.espncdn.com/i/teamlogos/soccer/500/2922.png",
  "levante": "https://a.espncdn.com/i/teamlogos/soccer/500/1538.png",
  "lev": "https://a.espncdn.com/i/teamlogos/soccer/500/1538.png",
  "málaga": "https://a.espncdn.com/i/teamlogos/soccer/500/99.png",
  "mcf": "https://a.espncdn.com/i/teamlogos/soccer/500/99.png",
  "osasuna": "https://a.espncdn.com/i/teamlogos/soccer/500/97.png",
  "osa": "https://a.espncdn.com/i/teamlogos/soccer/500/97.png",
  "racing santander": "https://a.espncdn.com/i/teamlogos/soccer/500/87.png",
  "racing": "https://a.espncdn.com/i/teamlogos/soccer/500/87.png",
  "rac": "https://a.espncdn.com/i/teamlogos/soccer/500/87.png",
  "rayo vallecano": "https://a.espncdn.com/i/teamlogos/soccer/500/101.png",
  "rayo": "https://a.espncdn.com/i/teamlogos/soccer/500/101.png",
  "ray": "https://a.espncdn.com/i/teamlogos/soccer/500/101.png",
  "real betis": "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
  "betis": "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
  "bet": "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
  "real madrid": "https://a.espncdn.com/i/teamlogos/soccer/500/86.png",
  "rma": "https://a.espncdn.com/i/teamlogos/soccer/500/86.png",
  "real sociedad": "https://a.espncdn.com/i/teamlogos/soccer/500/89.png",
  "rso": "https://a.espncdn.com/i/teamlogos/soccer/500/89.png",
  "sevilla": "https://a.espncdn.com/i/teamlogos/soccer/500/243.png",
  "sev": "https://a.espncdn.com/i/teamlogos/soccer/500/243.png",
  "valencia": "https://a.espncdn.com/i/teamlogos/soccer/500/94.png",
  "val": "https://a.espncdn.com/i/teamlogos/soccer/500/94.png",
  "villarreal": "https://a.espncdn.com/i/teamlogos/soccer/500/102.png",
  "vil": "https://a.espncdn.com/i/teamlogos/soccer/500/102.png",
  "ac milan": "https://a.espncdn.com/i/teamlogos/soccer/500/103.png",
  "milan": "https://a.espncdn.com/i/teamlogos/soccer/500/103.png",
  "mil": "https://a.espncdn.com/i/teamlogos/soccer/500/103.png",
  "as roma": "https://a.espncdn.com/i/teamlogos/soccer/500/104.png",
  "roma": "https://a.espncdn.com/i/teamlogos/soccer/500/104.png",
  "atalanta": "https://a.espncdn.com/i/teamlogos/soccer/500/105.png",
  "ata": "https://a.espncdn.com/i/teamlogos/soccer/500/105.png",
  "bologna": "https://a.espncdn.com/i/teamlogos/soccer/500/107.png",
  "bol": "https://a.espncdn.com/i/teamlogos/soccer/500/107.png",
  "cagliari": "https://a.espncdn.com/i/teamlogos/soccer/500/2925.png",
  "cag": "https://a.espncdn.com/i/teamlogos/soccer/500/2925.png",
  "como": "https://a.espncdn.com/i/teamlogos/soccer/500/2572.png",
  "fiorentina": "https://a.espncdn.com/i/teamlogos/soccer/500/109.png",
  "fio": "https://a.espncdn.com/i/teamlogos/soccer/500/109.png",
  "frosinone": "https://a.espncdn.com/i/teamlogos/soccer/500/4057.png",
  "fro": "https://a.espncdn.com/i/teamlogos/soccer/500/4057.png",
  "genoa": "https://a.espncdn.com/i/teamlogos/soccer/500/3263.png",
  "gen": "https://a.espncdn.com/i/teamlogos/soccer/500/3263.png",
  "internazionale": "https://a.espncdn.com/i/teamlogos/soccer/500/110.png",
  "inter milan": "https://a.espncdn.com/i/teamlogos/soccer/500/110.png",
  "int": "https://a.espncdn.com/i/teamlogos/soccer/500/110.png",
  "juventus": "https://a.espncdn.com/i/teamlogos/soccer/500/111.png",
  "juv": "https://a.espncdn.com/i/teamlogos/soccer/500/111.png",
  "lazio": "https://a.espncdn.com/i/teamlogos/soccer/500/112.png",
  "laz": "https://a.espncdn.com/i/teamlogos/soccer/500/112.png",
  "lecce": "https://a.espncdn.com/i/teamlogos/soccer/500/113.png",
  "lec": "https://a.espncdn.com/i/teamlogos/soccer/500/113.png",
  "monza": "https://a.espncdn.com/i/teamlogos/soccer/500/4007.png",
  "mon": "https://a.espncdn.com/i/teamlogos/soccer/500/174.png",
  "napoli": "https://a.espncdn.com/i/teamlogos/soccer/500/114.png",
  "nap": "https://a.espncdn.com/i/teamlogos/soccer/500/114.png",
  "parma": "https://a.espncdn.com/i/teamlogos/soccer/500/115.png",
  "par": "https://a.espncdn.com/i/teamlogos/soccer/500/6851.png",
  "sassuolo": "https://a.espncdn.com/i/teamlogos/soccer/500/3997.png",
  "sas": "https://a.espncdn.com/i/teamlogos/soccer/500/3997.png",
  "torino": "https://a.espncdn.com/i/teamlogos/soccer/500/239.png",
  "tor": "https://a.espncdn.com/i/teamlogos/soccer/500/239.png",
  "udinese": "https://a.espncdn.com/i/teamlogos/soccer/500/118.png",
  "udi": "https://a.espncdn.com/i/teamlogos/soccer/500/118.png",
  "venezia": "https://a.espncdn.com/i/teamlogos/soccer/500/17530.png",
  "ven": "https://a.espncdn.com/i/teamlogos/soccer/500/17530.png",
  "1. fc union berlin": "https://a.espncdn.com/i/teamlogos/soccer/500/598.png",
  "union berlin": "https://a.espncdn.com/i/teamlogos/soccer/500/598.png",
  "fcu": "https://a.espncdn.com/i/teamlogos/soccer/500/598.png",
  "bayer leverkusen": "https://a.espncdn.com/i/teamlogos/soccer/500/131.png",
  "leverkusen": "https://a.espncdn.com/i/teamlogos/soccer/500/131.png",
  "b04": "https://a.espncdn.com/i/teamlogos/soccer/500/131.png",
  "bayern munich": "https://a.espncdn.com/i/teamlogos/soccer/500/132.png",
  "bayern": "https://a.espncdn.com/i/teamlogos/soccer/500/132.png",
  "mun": "https://a.espncdn.com/i/teamlogos/soccer/500/132.png",
  "borussia dortmund": "https://a.espncdn.com/i/teamlogos/soccer/500/124.png",
  "dortmund": "https://a.espncdn.com/i/teamlogos/soccer/500/124.png",
  "dor": "https://a.espncdn.com/i/teamlogos/soccer/500/124.png",
  "borussia mönchengladbach": "https://a.espncdn.com/i/teamlogos/soccer/500/268.png",
  "gladbach": "https://a.espncdn.com/i/teamlogos/soccer/500/268.png",
  "bmg": "https://a.espncdn.com/i/teamlogos/soccer/500/268.png",
  "eintracht frankfurt": "https://a.espncdn.com/i/teamlogos/soccer/500/125.png",
  "frankfurt": "https://a.espncdn.com/i/teamlogos/soccer/500/125.png",
  "sge": "https://a.espncdn.com/i/teamlogos/soccer/500/125.png",
  "fc augsburg": "https://a.espncdn.com/i/teamlogos/soccer/500/3841.png",
  "augsburg": "https://a.espncdn.com/i/teamlogos/soccer/500/3841.png",
  "fca": "https://a.espncdn.com/i/teamlogos/soccer/500/3841.png",
  "fc cologne": "https://a.espncdn.com/i/teamlogos/soccer/500/122.png",
  "cologne": "https://a.espncdn.com/i/teamlogos/soccer/500/122.png",
  "koe": "https://a.espncdn.com/i/teamlogos/soccer/500/122.png",
  "hamburg sv": "https://a.espncdn.com/i/teamlogos/soccer/500/127.png",
  "hamburg": "https://a.espncdn.com/i/teamlogos/soccer/500/127.png",
  "hsv": "https://a.espncdn.com/i/teamlogos/soccer/500/127.png",
  "mainz": "https://a.espncdn.com/i/teamlogos/soccer/500/2950.png",
  "m05": "https://a.espncdn.com/i/teamlogos/soccer/500/2950.png",
  "rb leipzig": "https://a.espncdn.com/i/teamlogos/soccer/500/11420.png",
  "rbl": "https://a.espncdn.com/i/teamlogos/soccer/500/11420.png",
  "sc freiburg": "https://a.espncdn.com/i/teamlogos/soccer/500/126.png",
  "freiburg": "https://a.espncdn.com/i/teamlogos/soccer/500/126.png",
  "scf": "https://a.espncdn.com/i/teamlogos/soccer/500/126.png",
  "sc paderborn 07": "https://a.espncdn.com/i/teamlogos/soccer/500/3307.png",
  "paderborn": "https://a.espncdn.com/i/teamlogos/soccer/500/3307.png",
  "scp": "https://a.espncdn.com/i/teamlogos/soccer/500/2250.png",
  "sv elversberg": "https://a.espncdn.com/i/teamlogos/soccer/500/10388.png",
  "elversberg": "https://a.espncdn.com/i/teamlogos/soccer/500/10388.png",
  "elv": "https://a.espncdn.com/i/teamlogos/soccer/500/10388.png",
  "schalke 04": "https://a.espncdn.com/i/teamlogos/soccer/500/133.png",
  "schalke": "https://a.espncdn.com/i/teamlogos/soccer/500/133.png",
  "s04": "https://a.espncdn.com/i/teamlogos/soccer/500/133.png",
  "tsg hoffenheim": "https://a.espncdn.com/i/teamlogos/soccer/500/7911.png",
  "hoffenheim": "https://a.espncdn.com/i/teamlogos/soccer/500/7911.png",
  "tsg": "https://a.espncdn.com/i/teamlogos/soccer/500/7911.png",
  "vfb stuttgart": "https://a.espncdn.com/i/teamlogos/soccer/500/134.png",
  "stuttgart": "https://a.espncdn.com/i/teamlogos/soccer/500/134.png",
  "vfb": "https://a.espncdn.com/i/teamlogos/soccer/500/134.png",
  "werder bremen": "https://a.espncdn.com/i/teamlogos/soccer/500/137.png",
  "bremen": "https://a.espncdn.com/i/teamlogos/soccer/500/137.png",
  "svw": "https://a.espncdn.com/i/teamlogos/soccer/500/137.png",
  "aj auxerre": "https://a.espncdn.com/i/teamlogos/soccer/500/172.png",
  "auxerre": "https://a.espncdn.com/i/teamlogos/soccer/500/172.png",
  "aux": "https://a.espncdn.com/i/teamlogos/soccer/500/172.png",
  "as monaco": "https://a.espncdn.com/i/teamlogos/soccer/500/174.png",
  "monaco": "https://a.espncdn.com/i/teamlogos/soccer/500/174.png",
  "angers": "https://a.espncdn.com/i/teamlogos/soccer/500/7868.png",
  "ang": "https://a.espncdn.com/i/teamlogos/soccer/500/7868.png",
  "brest": "https://a.espncdn.com/i/teamlogos/soccer/500/6997.png",
  "le havre ac": "https://a.espncdn.com/i/teamlogos/soccer/500/3236.png",
  "hac": "https://a.espncdn.com/i/teamlogos/soccer/500/3236.png",
  "le mans": "https://a.espncdn.com/i/teamlogos/soccer/500/2697.png",
  "mns": "https://a.espncdn.com/i/teamlogos/soccer/500/2697.png",
  "lens": "https://a.espncdn.com/i/teamlogos/soccer/500/175.png",
  "rcl": "https://a.espncdn.com/i/teamlogos/soccer/500/175.png",
  "lille": "https://a.espncdn.com/i/teamlogos/soccer/500/166.png",
  "lill": "https://a.espncdn.com/i/teamlogos/soccer/500/166.png",
  "lorient": "https://a.espncdn.com/i/teamlogos/soccer/500/273.png",
  "lor": "https://a.espncdn.com/i/teamlogos/soccer/500/273.png",
  "lyon": "https://a.espncdn.com/i/teamlogos/soccer/500/167.png",
  "marseille": "https://a.espncdn.com/i/teamlogos/soccer/500/176.png",
  "olm": "https://a.espncdn.com/i/teamlogos/soccer/500/176.png",
  "nice": "https://a.espncdn.com/i/teamlogos/soccer/500/2502.png",
  "paris fc": "https://a.espncdn.com/i/teamlogos/soccer/500/6851.png",
  "paris saint-germain": "https://a.espncdn.com/i/teamlogos/soccer/500/160.png",
  "psg": "https://a.espncdn.com/i/teamlogos/soccer/500/160.png",
  "stade rennais": "https://a.espncdn.com/i/teamlogos/soccer/500/169.png",
  "rennes": "https://a.espncdn.com/i/teamlogos/soccer/500/169.png",
  "ren": "https://a.espncdn.com/i/teamlogos/soccer/500/169.png",
  "strasbourg": "https://a.espncdn.com/i/teamlogos/soccer/500/180.png",
  "str": "https://a.espncdn.com/i/teamlogos/soccer/500/180.png",
  "toulouse": "https://a.espncdn.com/i/teamlogos/soccer/500/179.png",
  "tou": "https://a.espncdn.com/i/teamlogos/soccer/500/179.png",
  "troyes": "https://a.espncdn.com/i/teamlogos/soccer/500/170.png",
  "try": "https://a.espncdn.com/i/teamlogos/soccer/500/170.png",
  "aek athens": "https://a.espncdn.com/i/teamlogos/soccer/500/887.png",
  "aek": "https://a.espncdn.com/i/teamlogos/soccer/500/887.png",
  "bodo/glimt": "https://a.espncdn.com/i/teamlogos/soccer/500/2980.png",
  "bodo": "https://a.espncdn.com/i/teamlogos/soccer/500/2980.png",
  "club brugge": "https://a.espncdn.com/i/teamlogos/soccer/500/570.png",
  "bru": "https://a.espncdn.com/i/teamlogos/soccer/500/570.png",
  "fc porto": "https://a.espncdn.com/i/teamlogos/soccer/500/437.png",
  "fcp": "https://a.espncdn.com/i/teamlogos/soccer/500/437.png",
  "fenerbahce": "https://a.espncdn.com/i/teamlogos/soccer/500/436.png",
  "fen": "https://a.espncdn.com/i/teamlogos/soccer/500/436.png",
  "feyenoord rotterdam": "https://a.espncdn.com/i/teamlogos/soccer/500/142.png",
  "feyenoord": "https://a.espncdn.com/i/teamlogos/soccer/500/142.png",
  "fey": "https://a.espncdn.com/i/teamlogos/soccer/500/142.png",
  "galatasaray": "https://a.espncdn.com/i/teamlogos/soccer/500/432.png",
  "gal": "https://a.espncdn.com/i/teamlogos/soccer/500/432.png",
  "lask linz": "https://a.espncdn.com/i/teamlogos/soccer/500/4411.png",
  "las": "https://a.espncdn.com/i/teamlogos/soccer/500/4411.png",
  "psv eindhoven": "https://a.espncdn.com/i/teamlogos/soccer/500/148.png",
  "psv": "https://a.espncdn.com/i/teamlogos/soccer/500/148.png",
  "sabah fk": "https://a.espncdn.com/i/teamlogos/soccer/500/21922.png",
  "sabah": "https://a.espncdn.com/i/teamlogos/soccer/500/21922.png",
  "sab": "https://a.espncdn.com/i/teamlogos/soccer/500/21922.png",
  "shakhtar donetsk": "https://a.espncdn.com/i/teamlogos/soccer/500/493.png",
  "shakhtar": "https://a.espncdn.com/i/teamlogos/soccer/500/493.png",
  "shk": "https://a.espncdn.com/i/teamlogos/soccer/500/493.png",
  "slavia prague": "https://a.espncdn.com/i/teamlogos/soccer/500/494.png",
  "slp": "https://a.espncdn.com/i/teamlogos/soccer/500/494.png",
  "slovan bratislava": "https://a.espncdn.com/i/teamlogos/soccer/500/521.png",
  "s bratislava": "https://a.espncdn.com/i/teamlogos/soccer/500/521.png",
  "slb": "https://a.espncdn.com/i/teamlogos/soccer/500/521.png",
  "sporting cp": "https://a.espncdn.com/i/teamlogos/soccer/500/2250.png",
  "sporting": "https://a.espncdn.com/i/teamlogos/soccer/500/2250.png",
  "viking fk": "https://a.espncdn.com/i/teamlogos/soccer/500/510.png",
  "vik": "https://a.espncdn.com/i/teamlogos/soccer/500/510.png"
};

/**
 * Normalizes a team name for reliable lookup in the dictionary.
 */
function normalizeTeamKey(str: string): string {
  return str
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/^(\d+\.?\s*(fc|fsv|vfb|vfl|rcd|rc|ud|cd|aj|as|ssc|us|acf|bsc|ac)?\s*)/i, "")
    .replace(/^(fc|vfb|vfl|rcd|rc|ud|cd|aj|as|ssc|us|acf|bsc|ac|afc)\s+/i, "")
    .replace(/\s+(fc|cf|sc|sv|hsc|sco|united|wanderers|albion)$/i, "")
    .trim();
}

/**
 * Returns the official ESPN logo URL for a team name, id, or shortName.
 */
export function getTeamLogoUrl(nameOrId?: string, fallbackShortName?: string): string {
  if (!nameOrId && !fallbackShortName) {
    return DEFAULT_TEAM_LOGO;
  }

  // If already a valid URL, return it
  if (nameOrId && (nameOrId.startsWith("http://") || nameOrId.startsWith("https://"))) {
    if (nameOrId.includes("default-team-logo.png") || nameOrId.includes("/6410.png")) {
      return "https://a.espncdn.com/i/teamlogos/soccer/500/598.png";
    }
    return nameOrId;
  }

  const rawKey = (nameOrId || "").toLowerCase().trim();
  if (ESPN_TEAM_LOGOS[rawKey]) {
    return ESPN_TEAM_LOGOS[rawKey];
  }

  // Check normalized key
  const normKey = normalizeTeamKey(rawKey);
  if (ESPN_TEAM_LOGOS[normKey]) {
    return ESPN_TEAM_LOGOS[normKey];
  }

  // Try checking shortName
  if (fallbackShortName) {
    const cleanShort = fallbackShortName.toLowerCase().trim();
    if (ESPN_TEAM_LOGOS[cleanShort]) {
      return ESPN_TEAM_LOGOS[cleanShort];
    }
  }

  // Try partial matching keys
  for (const [k, url] of Object.entries(ESPN_TEAM_LOGOS)) {
    if (normKey && (normKey === k || normKey.includes(k) || k.includes(normKey))) {
      return url;
    }
    if (rawKey.includes(k) || k.includes(rawKey)) {
      return url;
    }
  }

  // Default clean soccer ball badge fallback
  return DEFAULT_TEAM_LOGO;
}
